version: '3'

services:
  cocoroiki-proxy:
    image: nginx:alpine
    container_name: cocoroiki-proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1234:80
    depends_on:
      - cocoroiki-bff
      - cocoroiki-cms

  cocoroiki-bff:
    build: ./bff
    container_name: cocoroiki-bff
    volumes:
      - ./bff:/go/src/app

  cocoroiki-cms:
    image: node:16-alpine
    container_name: cocoroiki-cms
    working_dir: /app
    volumes:
      - ./cms:/app
    ports:
      - 1337:1337
    command: >
      sh -c "
        yarn &&
        yarn add @strapi/plugin-documentation &&
        yarn develop
      "

  cocoroiki-db:
    image: mysql:5.7
    container_name: cocoroiki-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cocoroiki
      MYSQL_USER: cocoroiki
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  cocoroiki-api:
    image: python:3.8
    ports:
      - 8080:8080
    container_name: cocoroiki-api
    working_dir: /api
    volumes:
      - ./api:/api
    command: >
      sh -c "
        pip install -r requirements.txt
        pip install fastapi uvicorn
        uvicorn main:app --reload --host 0.0.0.0 --port 8080
      "

volumes:
  db:
