version: '3'

services:
  proxy:
    image: nginx:alpine
    container_name: cocoroiki-proxy
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1234:80
    depends_on:
      - app
      - api

  app:
    build: .
    container_name: cocoroiki-bff
    volumes:
      - ./:/go/src/app

  api:
    image: node:16-alpine
    container_name: cocoroiki-api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - 1337:1337
    command: >
      sh -c "
        yarn &&
        yarn add @strapi/plugin-documentation &&
        yarn develop
      "

  db:
    image: mysql:5.7
    container_name: cocoroiki-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Tokyo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cocoroiki
      MYSQL_USER: cocoroiki
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "3000:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "3001:8080"
    volumes:
      - ./mock:/mock
    environment:
      SWAGGER_JSON: /mock/openapi.yml

  swagger-api:
    image: stoplight/prism:4
    container_name: "swagger-api"
    ports:
      - "3002:4010"
    command: mock -h 0.0.0.0 /mock/openapi.yml -d
    volumes:
      - ./mock:/mock

volumes:
  db:
