version: "3"

services:

  app:
    image: python:3.8
    ports:
      - 8080:8080
    container_name: app
    working_dir: /api
    volumes:
      - .:/api
    command: >
      sh -c "
        pip install -r requirements.txt
        pip install fastapi uvicorn
        uvicorn main:app --reload --host 0.0.0.0 --port 8080
      "

